red_line1 = ['Shaheed Sthal-New Bus Adda', 'Hindon River', 'Arthala', 'Mohan Nagar', 'Shyam Park', 'Maj M.Sharma-Rajendra Nagar', 'Raj Bagh','Shahid Nagar', 'Dilshad Garden', 'Jhilmil', 'Mansarovar Park', 'Shahdara','Welcome', 'Seelampur','Shastri Park', 'Kashmere Gate', 'Tis Hazari', 'Pul Bangash', 'Pratap Nagar', 'Shastri Nagar', 'Inderlok', 'Kanhaiya Nagar', 'Keshav Puram', 'Netaji Subhash Place', 'Kohat Enclave', 'Pitampura', 'Rohini East', 'Rohini West','Rithala']

yellow_line2 = ['Samaypur Badli', 'RohiniSE18', 'Haider Pur', 'Jahangir Puri', 'Adarsh Nagar', 'Azadpur', 'Model Town', 'GTB Nagar', 'Vishwa Vidalaya', 'Vidhan Sabha', 'Civil Lines', 'Kashmere Gate', 'Chandni Chowk', 'Chawri Bazar', 'New Delhi', 'Rajiv Chowk', 'Patel Chowk', 'Central Secretariat', 'Udyog Bhavan', 'Race Course', 'Jor Bagh', 'INA', 'AIIMS', 'Green Park', 'Hauzkhas', 'Malaviya Nagar', 'Saket', 'Qutab Minar', 'Chhatar Pur', 'Sultan Pur', 'Ghitorny', 'Arjan Garh', 'Guru DronaCharya', 'Sikanderpur', 'MG Road', 'Iffco Chowk', 'Huda City Centre']

blue_line3 = ['Noida Electronic City', 'Sector-62 Noida', 'Sector-59 Noida', 'Sector-61 Noida', 'Sector-52 Noida', 'Sector-34 Noida', 'Noida City Center', 'Golf Course', 'Botanical Garden L-8', 'Noida Sec18', 'Noida Sec16', 'Noida Sec15', 'New Ashok Nagar', 'Mayur VPH1E', 'Mayur VPH1', 'Akshardham', 'Yamuna Bank', 'Indraprastha', 'Pragati Maidan', 'Mandi House', 'Barakhamba Road', 'R K Ashram', 'Jhandewalan', 'Karol Bagh', 'Rajendra Place', 'Patel Nagar', 'Shadipur', 'Kirti Nagar', 'Moti Nagar', 'Ramesh Nagar', 'Rajouri Garden', 'Tagore Garden', 'Subhash Nagar', 'Tilak Nagar', 'Janak Puri E', 'Janak Puri W', 'Uttam Ngr E', 'Uttam Ngr W', 'Nawada', 'Dwarka Mor', 'Dwarka', 'Dwarka SE14', 'Dwarka SE13', 'Dwarka SE12', 'Dwarka SE11', 'Dwarka SE10', 'Dwarka SE09', 'Dwarka Sec08', 'Dwarka Sec21']

blue_line4 = ['Vaishali', 'Kaushambi', 'Anand Vihar ISBT', 'Karkardooma', 'Preet Vihar', 'Nirman Vihar', 'Laxmi Nagar']

green_line5 = ['Kirti Nagar', 'Sat Guru Ram Singh', 'Inderlok', 'Ashok Park Main', 'Punjabi Bagh', 'Shivaji Park', 'Madi Pur', 'Paschim V E', 'Paschim V W', 'Peera Garhi', 'Udyog Nagar', 'Maharaja Surajmal Stadium', 'Nangloi', 'Nangloi Railway Station', 'Rajdhani Park', 'Mundka', 'Mundka IA', 'Ghevra', 'Tikri Kalan', 'Tikri Border', 'Pandit Shree Ram Sharma', 'Bahadurgarh City','Brigadier Hoshiyar Singh']

violet_line6 = ['Kashmere Gate', 'Lal Quila', 'Jama Masjid', 'Delhi Gate', 'ITO', 'Mandi House', 'Janpath', 'Central Secretariat', 'Khan Market', 'JLN Stadium', 'Jangpura', 'Lajpat Nagar', 'Moolchand', 'Kailash Colony', 'Nehru Place', 'Kalkaji Mandir', 'Gobind Puri', 'Harkesh Nagar Okhla', 'Jasola Apollo', 'Sarita Vihar', 'Mohan Estate', 'Tughlakabad', 'Badarpur', 'Sarai', 'NHPC Chowk', 'Mewala Maharajpur', 'Sector 28', 'Badkal Mor', 'Faridabad Old', 'Neelam Chowk Ajronda', 'Bata Chowk', 'Escorts Mujesar', 'Sant Surdas Sihi', 'Raja Nahar Singh']

pink_line7 = ['Majlis Park', 'Azadpur', 'Shalimar Bagh', 'Netaji Subhash Place', 'Shakurpur', 'Punjabi Bagh West', 'ESI Hospital', 'Rajouri Garden L-7', 'Mayapuri', 'Naraina Vihar', 'Delhi Cantt', 'DD South Campus', 'SV Moti Bagh', 'Bhikaji Cama Place', 'Sarojini Nagar', 'INA', 'South Extension', 'Lajpat Nagar', 'Vinobapuri', 'Ashram', 'Hazrat Nizamuddin', 'Mayur VPH1', 'Mayur VPKT1', 'Trilokpuri', 'East Vinod Nagar', 'Mandawali-West Vinod Nagar', 'IP Extension', 'Anand Vihar ISBT', 'Karkardooma', 'Krishna Nagar', 'East Azad Nagar', 'Welcome', 'Jaffrabad', 'Maujpur', 'Gokulpuri', 'Johri Enclave', 'Shiv Vihar']

magenta_line8 = ['Botanical Garden L-8', 'Okhla Bird Sanctuary', 'Kalindi Kunj', 'Jasola Vihar Shaheen Bagh', 'Okhla Vihar', 'Jamia Millia Islamia', 'Sukhdev Vihar', 'Okhla NSIC', 'Nehru Enclave', 'G.K.Enclave-I', 'Chirag Delhi', 'Panchsheel Park', 'Hauzkhas', 'IIT', 'R.K. Puram', 'Munirka', 'Vasant Vihar', 'Shankar Vihar', 'IGD Airport', 'Sadar Bazar', 'PALAM', 'Dashrathpuri', 'Dabri Mor', 'Janakpuri West L-8']